name: Cleanup old images

'on':
  schedule:
    - cron: 0 1 * * 0
  workflow_dispatch: null

jobs:
  cleanup:
    runs-on: ubuntu-latest

    permissions:
      packages: write

    steps:
      - uses: actions/delete-package-versions@v5
        with:
          package-name: mushroom-os
          package-type: container
          min-versions-to-keep: 3
          token: '${{ secrets.GITHUB_TOKEN }}'
